name: kobe_prediction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - mlflow==2.8.0
    - pycaret==3.1.0
    - scikit-learn==1.3.2
    - pandas==2.0.3
    - numpy==1.24.3
    - streamlit==1.28.2
    - matplotlib==3.7.2
    - seaborn==0.13.0
    - pyarrow==14.0.0